<?php

$legacyContentTypes = array(
	"CONTENT_GRASS"=>1,
	"CONTENT_TREE"=>4,
	"CONTENT_LEAVES"=>5,
	"CONTENT_GRASS_FOOTSTEPS"=>6,
	"CONTENT_MESE"=>7,
	"CONTENT_MUD"=>8,
	"CONTENT_CLOUD"=>10,
	"CONTENT_COALSTONE"=>11,
	"CONTENT_WOOD"=>12,
	"CONTENT_SAND"=>13,
	"CONTENT_COBBLE"=>18,
	"CONTENT_STEEL"=>19,
	"CONTENT_GLASS"=>20,
	"CONTENT_MOSSYCOBBLE"=>22,
	"CONTENT_GRAVEL"=>23,
	"CONTENT_SANDSTONE"=>24,
	"CONTENT_CACTUS"=>25,
	"CONTENT_BRICK"=>26,
	"CONTENT_CLAY"=>27,
	"CONTENT_PAPYRUS"=>28,
	"CONTENT_BOOKSHELF"=>29,
);

?>
